# Generated by Django 2.2.6 on 2019-10-07 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('dl_applied', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('winner', models.CharField(max_length=50)),
                ('win_by_runs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('win_by_wickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('player_of_match', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('umpire1', models.CharField(max_length=50)),
                ('umpire2', models.CharField(max_length=50)),
                ('umpire3', models.CharField(max_length=50)),
            ],
        ),
    ]
