# Generated by Django 2.2.6 on 2019-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0003_auto_20191007_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='dl_applied',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_runs',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_wickets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
