# Generated by Django 2.2.6 on 2019-10-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0005_delieveries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delieveries',
            old_name='match',
            new_name='match_id',
        ),
    ]
