# Generated by Django 2.2.6 on 2019-10-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0006_auto_20191007_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delieveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
