# Generated by Django 2.2.6 on 2019-10-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0007_auto_20191007_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delieveries',
            new_name='Deliveries',
        ),
    ]
