# Generated by Django 2.2.6 on 2019-10-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0008_auto_20191007_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match',
            new_name='match_id',
        ),
    ]
