# Generated by Django 2.2.6 on 2019-10-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0009_auto_20191007_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
