# Generated by Django 2.2.6 on 2019-10-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0010_auto_20191007_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deliveries',
            new_name='Delivery',
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
    ]
