# Generated by Django 2.2.6 on 2019-10-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0011_auto_20191007_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
