# Generated by Django 2.2.6 on 2019-10-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0013_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
